export const SUMMARY_ACTION_TYPES = {
    FETCH_SUMMARY_START: 'summary/FETCH_SUMMARY_START',
    FETCH_SUMMARY_SUCCESS: 'summary/FETCH_SUMMARY_SUCCESS',
    FETCH_SUMMARY_FAILED: 'summary/FETCH_SUMMARY_FAILED',
    CLEAR_SUMMARY_DATA: 'summary/CLEAR_SUMMARY_DATA'
};